'use client';

import { useEffect, useState, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import jsPDF from 'jspdf';

type Status = 'loading' | 'letter' | 'notice' | 'error';

function SuccessContent() {
  const searchParams = useSearchParams();
  const sessionId = searchParams.get('session_id');

  const [status, setStatus] = useState<Status>('loading');
  const [letter, setLetter] = useState('');
  const [notice, setNotice] = useState('');     // missing_info / out_of_scope message
  const [error, setError] = useState('');

  const generateLetter = useCallback(async () => {
    if (!sessionId) {
      setError('Invalid session. Please return to the home page.');
      setStatus('error');
      return;
    }

    setStatus('loading');
    setError('');

    try {
      // AUDIT FIX (P3): we no longer read form data from localStorage. The
      // payload lives server-side keyed to this paid Stripe session; we just
      // hand the server the session id and it verifies payment + loads the data.
      const response = await fetch('/api/generate-letter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sessionId }),
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        setError(
          data?.error ||
            'Something went wrong generating your letter. Please contact support with your payment confirmation.'
        );
        setStatus('error');
        return;
      }

      if (data.type === 'letter') {
        setLetter(data.letter);
        setStatus('letter');
      } else if (data.type === 'missing_info' || data.type === 'out_of_scope') {
        setNotice(data.message || '');
        setStatus('notice');
      } else {
        setError('Unexpected response. Please contact support with your payment confirmation.');
        setStatus('error');
      }
    } catch {
      setError(
        'Something went wrong generating your letter. Please contact support with your payment confirmation.'
      );
      setStatus('error');
    }
  }, [sessionId]);

  useEffect(() => {
    generateLetter();
  }, [generateLetter]);

  const downloadPDF = () => {
    const pdf = new jsPDF({ unit: 'pt', format: 'letter' });

    const pageWidth = 612;
    const pageHeight = 792;
    const marginX = 40;
    const contentTop = 80;
    const bottomMargin = 56; // leave room for the footer
    const lineHeight = 14;
    const maxY = pageHeight - bottomMargin;

    const drawHeader = () => {
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text('TenantShield', marginX, 40);
      pdf.setDrawColor(200, 200, 200);
      pdf.line(marginX, 50, pageWidth - marginX, 50);
    };

    const drawFooter = () => {
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text(
        'Generated by TenantShield — This is not legal advice',
        marginX,
        pageHeight - 30
      );
    };

    drawHeader();
    pdf.setFontSize(11);
    pdf.setTextColor(0, 0, 0);

    const lines = pdf.splitTextToSize(letter, pageWidth - marginX * 2);
    let y = contentTop;

    lines.forEach((line: string) => {
      if (y > maxY) {
        drawFooter();     // P11: footer drawn on every page, at a valid y
        pdf.addPage();
        drawHeader();
        pdf.setFontSize(11);
        pdf.setTextColor(0, 0, 0);
        y = contentTop;
      }
      pdf.text(line, marginX, y);
      y += lineHeight;
    });

    drawFooter(); // footer on the final page
    pdf.save('TenantShield_Demand_Letter.pdf');
  };

  if (status === 'loading') {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400 mx-auto mb-4"></div>
          <p className="text-slate-300 text-lg">Payment confirmed. Generating your letter...</p>
          <p className="text-slate-500 text-sm mt-2">This takes about 15-20 seconds.</p>
        </div>
      </div>
    );
  }

  if (status === 'error') {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center px-4">
        <div className="bg-red-900/30 border border-red-500 rounded-lg p-6 max-w-lg text-center">
          <p className="text-red-300 text-lg font-semibold mb-2">Something went wrong</p>
          <p className="text-slate-400 text-sm">{error}</p>
          {/* P9: your payment is safe and your details are stored — let the user retry without re-paying. */}
          <div className="mt-5 flex items-center justify-center gap-4">
            <button
              onClick={generateLetter}
              className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-lg text-sm font-medium transition-colors"
            >
              Try again
            </button>
            <a href="/" className="text-blue-400 underline text-sm">Return to home</a>
          </div>
          <p className="text-slate-500 text-xs mt-4">
            Your payment was received. You can retry generation here, or email{' '}
            <a href="mailto:support@gettenantshield.com" className="underline">
              support@gettenantshield.com
            </a>{' '}
            with your payment confirmation and we&apos;ll send your letter.
          </p>
        </div>
      </div>
    );
  }

  if (status === 'notice') {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center px-4">
        <div className="bg-slate-800 border border-slate-600 rounded-lg p-6 max-w-lg text-center">
          <p className="text-white text-lg font-semibold mb-2">We need a little more detail</p>
          <p className="text-slate-300 text-sm whitespace-pre-wrap">{notice}</p>
          <div className="mt-5 flex items-center justify-center gap-4">
            <button
              onClick={generateLetter}
              className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-lg text-sm font-medium transition-colors"
            >
              Try again
            </button>
            <a href="/" className="text-blue-400 underline text-sm">Return to home</a>
          </div>
          <p className="text-slate-500 text-xs mt-4">
            Need help? Email{' '}
            <a href="mailto:support@gettenantshield.com" className="underline">
              support@gettenantshield.com
            </a>{' '}
            with your payment confirmation.
          </p>
        </div>
      </div>
    );
  }

  // status === 'letter'
  return (
    <div className="min-h-screen bg-slate-900 py-10 px-4">
      <div className="max-w-3xl mx-auto">

        {/* Top nav bar */}
        <div className="flex items-center justify-between mb-8">
          <a
            href="/"
            className="text-slate-400 hover:text-white text-sm flex items-center gap-1 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            TenantShield
          </a>
          <a
            href="/generate"
            className="text-sm text-amber-500 hover:text-amber-400 font-medium transition-colors"
          >
            Generate another letter →
          </a>
        </div>

        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white">Your Demand Letter</h1>
            <p className="text-slate-400 text-sm mt-1">Payment confirmed · TenantShield</p>
          </div>
          <button
            onClick={downloadPDF}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </button>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-8 mb-6">
          <pre className="whitespace-pre-wrap font-serif text-gray-800 text-sm leading-relaxed">
            {letter}
          </pre>
        </div>

        <div className="bg-slate-800 rounded-xl border border-slate-700 p-6">
          <h3 className="font-semibold text-white mb-4">Next Steps</h3>
          <ol className="space-y-3 text-sm text-slate-300">
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">1</span>
              <div><strong className="text-white">Download the PDF</strong> using the button above.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">2</span>
              <div><strong className="text-white">Print and sign</strong> the letter with blue or black ink.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">3</span>
              <div><strong className="text-white">Send via USPS Certified Mail</strong> with Return Receipt. Keep your tracking number and green card.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">4</span>
              <div><strong className="text-white">Wait for the deadline</strong> stated in the letter. Most landlords respond once they realize you know the law.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">5</span>
              <div><strong className="text-white">If no response by deadline:</strong> File in small claims court. This letter becomes key evidence that you followed proper procedure.</div>
            </li>
          </ol>
        </div>

        {/* Bottom CTA */}
        <div className="mt-8 text-center">
          <p className="text-slate-400 text-sm mb-3">Need a letter for another property?</p>
          <a
            href="/generate"
            className="inline-block bg-amber-700 hover:bg-amber-800 text-white px-8 py-3 rounded-lg text-sm font-medium transition-colors"
          >
            Generate Another Letter
          </a>
        </div>

        <p className="text-slate-500 text-xs text-center mt-6">
          TenantShield generates demand letters for informational purposes. This is not legal advice. Consult an attorney for legal guidance specific to your situation.
        </p>

      </div>
    </div>
  );
}

export default function SuccessPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400"></div>
      </div>
    }>
      <SuccessContent />
    </Suspense>
  );
}
