'use client';

import { useEffect, useState, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import jsPDF from 'jspdf';

function SuccessContent() {
  const searchParams = useSearchParams();
  const sessionId = searchParams.get('session_id');
  const [letter, setLetter] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const generateLetter = async () => {
      try {
        const formDataStr = localStorage.getItem('tenantshield_pending_form');
        if (!formDataStr) {
          setError('Form data not found. Please return to the home page and try again.');
          setLoading(false);
          return;
        }

        const formData = JSON.parse(formDataStr);

        const response = await fetch('/api/generate-letter', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(formData),
        });

        if (!response.ok) throw new Error('Generation failed');

        const data = await response.json();
        setLetter(data.letter);
        localStorage.removeItem('tenantshield_pending_form');
      } catch {
        setError('Something went wrong generating your letter. Please contact support with your payment confirmation.');
      } finally {
        setLoading(false);
      }
    };

    if (sessionId) {
      generateLetter();
    } else {
      setError('Invalid session. Please return to the home page.');
      setLoading(false);
    }
  }, [sessionId]);

  const downloadPDF = () => {
    const pdf = new jsPDF({
      unit: 'pt',
      format: 'letter',
    });

    // Letterhead area
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('TenantShield', 40, 40);
    pdf.setDrawColor(200, 200, 200);
    pdf.line(40, 50, 572, 50);

    // Letter content
    pdf.setFontSize(11);
    pdf.setTextColor(0, 0, 0);
    
    const lines = pdf.splitTextToSize(letter, 500);
    let yPosition = 80;
    const lineHeight = 14;
    const pageHeight = 752;
    
    lines.forEach((line: string) => {
      if (yPosition > pageHeight) {
        pdf.addPage();
        yPosition = 40;
      }
      pdf.text(line, 40, yPosition);
      yPosition += lineHeight;
    });

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(100, 100, 100);
    const footerY = pageHeight + 20;
    pdf.text('Generated by TenantShield - This is not legal advice', 40, footerY);

    pdf.save('TenantShield_Demand_Letter.pdf');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400 mx-auto mb-4"></div>
          <p className="text-slate-300 text-lg">Payment confirmed. Generating your letter...</p>
          <p className="text-slate-500 text-sm mt-2">This takes about 15-20 seconds.</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center px-4">
        <div className="bg-red-900/30 border border-red-500 rounded-lg p-6 max-w-lg text-center">
          <p className="text-red-300 text-lg font-semibold mb-2">Something went wrong</p>
          <p className="text-slate-400 text-sm">{error}</p>
          <a href="/" className="mt-4 inline-block text-blue-400 underline text-sm">Return to home</a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-900 py-10 px-4">
      <div className="max-w-3xl mx-auto">

        {/* Top nav bar */}
        <div className="flex items-center justify-between mb-8">
          <a
            href="/"
            className="text-slate-400 hover:text-white text-sm flex items-center gap-1 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            TenantShield
          </a>
          <a
            href="/generate"
            className="text-sm text-amber-500 hover:text-amber-400 font-medium transition-colors"
          >
            Generate another letter →
          </a>
        </div>

        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white">Your Demand Letter</h1>
            <p className="text-slate-400 text-sm mt-1">Payment confirmed · TenantShield</p>
          </div>
          <button
            onClick={downloadPDF}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </button>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-8 mb-6">
          <pre className="whitespace-pre-wrap font-serif text-gray-800 text-sm leading-relaxed">
            {letter}
          </pre>
        </div>

        <div className="bg-slate-800 rounded-xl border border-slate-700 p-6">
          <h3 className="font-semibold text-white mb-4">Next Steps</h3>
          <ol className="space-y-3 text-sm text-slate-300">
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">1</span>
              <div><strong className="text-white">Download the PDF</strong> using the button above.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">2</span>
              <div><strong className="text-white">Print and sign</strong> the letter with blue or black ink.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">3</span>
              <div><strong className="text-white">Send via USPS Certified Mail</strong> with Return Receipt. Keep your tracking number and green card.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">4</span>
              <div><strong className="text-white">Wait for the deadline</strong> stated in the letter. Most landlords respond once they realize you know the law.</div>
            </li>
            <li className="flex gap-3">
              <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-xs">5</span>
              <div><strong className="text-white">If no response by deadline:</strong> File in small claims court. This letter becomes key evidence that you followed proper procedure.</div>
            </li>
          </ol>
        </div>

        {/* Bottom CTA */}
        <div className="mt-8 text-center">
          <p className="text-slate-400 text-sm mb-3">Need a letter for another property?</p>
          <a
            href="/generate"
            className="inline-block bg-amber-700 hover:bg-amber-800 text-white px-8 py-3 rounded-lg text-sm font-medium transition-colors"
          >
            Generate Another Letter
          </a>
        </div>

        <p className="text-slate-500 text-xs text-center mt-6">
          TenantShield generates demand letters for informational purposes. This is not legal advice. Consult an attorney for legal guidance specific to your situation.
        </p>

      </div>
    </div>
  );
}

export default function SuccessPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-400"></div>
      </div>
    }>
      <SuccessContent />
    </Suspense>
  );
}
